### ISSUE TITLE
Unable to access 'path.scripts'

### ISSUE THREAD

**Issue by aashish** [graphaware/graph-aided-search-demo#1]
I am getting following error after running the command
```
$ docker-compose up 
```
Error:
```
Refer to the log for complete error details.
elastic_container | Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
elastic_container | Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
elastic_container | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
elastic_container | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
elastic_container | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
elastic_container | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
elastic_container | 	at java.nio.file.Files.createDirectory(Files.java:674)
elastic_container | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
elastic_container | 	at java.nio.file.Files.createDirectories(Files.java:767)
elastic_container | 	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
elastic_container | 	at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
elastic_container | 	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:248)
elastic_container | 	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
elastic_container | 	at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:196)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
elastic_container | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
elastic_container | Refer to the log for complete error details.
elastic_container | Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)

```

Thank you,
Aashish

**Comment by espiegelberg** [comment]
Looking at the error log you've provided, I see:

...
java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
...

In a nutshell, your JVM is unable to access this directory. This path references ElasticSearch, which the sample docker-compose.yml makes no use of. So my guess is that you are running ElasticSearch on your machine that is somehow conflicting with the spinning up of the Neo4j nodes within Docker. Unfortunately, as ElasticSearch is outside the scope of my sample script, I can't be more helpful other than to suggest ensuring that this directory exists and/or to shut down the ElasticSearch instance.

**Comment by aashish** [comment]
I am not running any ElasticSearch instance from outside(from my machine). ElasticSearch server is running, when I execute the following commands directly as

```
$ docker pull elasticsearch
$ docker run -p 9200:9200 --name=elastic_container elasticsearch
```
The problem exists only when I run the sample script with
```
$ docker-compose up 
```
Tried updating ElasticSearch version to 5.4.x or latest in `docker-compose.yml`.
But no luck!!

Tried directly from docker container 
```
$ elasticsearch/bin/plugin install com.graphaware.es/graph-aided-search/2.3.2.0
``` 
ERROR: Unknown plugin com.graphaware.es/graph-aided-search/2.3.2.0


How to ensure /usr/share/elasticsearch/config/scripts? 


Thank you,
Aashish

**Comment by espiegelberg** [comment]
Unfortunately I am not able to provide any insight or additional help. My sample script doesn't make use of ElasticSearch or graph-aided-search in any way, so I don't have an understanding of how that fits into the picture on your machine.

**Comment by espiegelberg** [comment]
I now realize that the repository you're working with is graph-aided-search-demo rather than a one I mistakenly thought it was. Sorry for the confusion.

Another GraphAware member, one more familiar with this project, will follow up and help to resolve your issue shortly.

**Comment by aashish** [comment]
The following works on my machine but not in docker container
```
$ elasticsearch/bin/plugin install com.graphaware.es/graph-aided-search/2.3.2.0

A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - removes a plugin from Elasticsearch

Non-option arguments:
command              

Option         Description        
------         -----------        
-h, --help     show help          
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin com.graphaware.es/graph-aided-search/2.3.2.0

```

**Comment by ikwattro** [comment]
@aashish 

Would you be able to provide the logs of the full docker-compose debug.

Also you created the network and set it in your env right ?

Here I just ran the full stuff and there is no issue . : 

```
ikwattro@mbp666 ~/dev> cd graph-aided-search-demo/
ikwattro@mbp666 ~/d/graph-aided-search-demo> docker network create --driver bridge gas
89ffce43a5ebf7dafe5167f133bcbf199398c97061a9aebfe4427c1a2e46d49c
ikwattro@mbp666 ~/d/graph-aided-search-demo> set -x NETWORK "gas"
ikwattro@mbp666 ~/d/graph-aided-search-demo> docker-compose up
Pulling neo4j (neo4j:2.3.2-enterprise)...
2.3.2-enterprise: Pulling from library/neo4j
723254a2c089: Pull complete
abe15a44e12f: Pull complete
409a28e3cc3d: Pull complete
a9511c68044a: Pull complete
9d1b16e30bc8: Pull complete
0fc5a09c9242: Pull complete
d34976006493: Pull complete
3b70003f0c10: Pull complete
d31c2020f2c7: Pull complete
8a2274cd5a97: Pull complete
ca4c348e78d5: Pull complete
c29c7bfc233b: Pull complete
80991cd7cd32: Pull complete
Digest: sha256:8749aa6609a304acaff9ac98118466fb3d20975acac2337233a94e23964a5245
Status: Downloaded newer image for neo4j:2.3.2-enterprise
Pulling elastic (elasticsearch:2.2.2)...
2.2.2: Pulling from library/elasticsearch
386a066cd84a: Pull complete
75ea84187083: Pull complete
3e2e387eb26a: Pull complete
eef540699244: Pull complete
1624a2f8d114: Pull complete
7018f4ec6e0a: Pull complete
6ca3bc2ad3b3: Pull complete
424638b495a6: Pull complete
2ff72d0b7bea: Pull complete
9d25542ccc02: Pull complete
7764c111a5c7: Pull complete
a076ea41b544: Pull complete
4841e9c2a909: Pull complete
ed491141ede1: Pull complete
Digest: sha256:c243ff1ee18aed0680dcbe0abaeacdbf59fa6b35a2a902262787f841de6d7b88
Status: Downloaded newer image for elasticsearch:2.2.2
Creating neo4j ...
Creating elastic_container ...
Creating neo4j
Creating neo4j ... done
Attaching to elastic_container, neo4j
elastic_container | [2018-01-30 20:27:52,531][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
elastic_container | [2018-01-30 20:27:52,831][INFO ][node                     ] [Kasper Cole] version[2.2.2], pid[1], build[fcc01dd/2016-03-29T08:49:35Z]
elastic_container | [2018-01-30 20:27:52,831][INFO ][node                     ] [Kasper Cole] initializing ...
neo4j      | WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
neo4j      | Starting Neo4j Server console-mode...
elastic_container | [2018-01-30 20:27:53,768][INFO ][plugins                  ] [Kasper Cole] modules [lang-expression, lang-groovy], plugins [graph-aided-search], sites []
elastic_container | [2018-01-30 20:27:53,799][INFO ][env                      ] [Kasper Cole] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [55.9gb], net total_space [62.7gb], spins? [possibly], types [ext4]
elastic_container | [2018-01-30 20:27:53,800][INFO ][env                      ] [Kasper Cole] heap size [1007.3mb], compressed ordinary object pointers [true]
neo4j      | 2018-01-30 20:27:54.231+0000 INFO  No SSL certificate found, generating a self-signed certificate..
neo4j      | 2018-01-30 20:27:55.721+0000 INFO  Initiating metrics..
elastic_container | [2018-01-30 20:27:57,577][INFO ][node                     ] [Kasper Cole] initialized
elastic_container | [2018-01-30 20:27:57,578][INFO ][node                     ] [Kasper Cole] starting ...
elastic_container | [2018-01-30 20:27:57,741][INFO ][transport                ] [Kasper Cole] publish_address {172.20.0.2:9300}, bound_addresses {0.0.0.0:9300}
elastic_container | [2018-01-30 20:27:57,752][INFO ][discovery                ] [Kasper Cole] docker/VJAN2n_xT8elCP2ugcF8qw
neo4j      | 2018-01-30 20:28:00.376+0000 INFO  Successfully started database
neo4j      | 2018-01-30 20:28:00.404+0000 INFO  Starting HTTP on port 7474 (2 threads available)
neo4j      | 2018-01-30 20:28:00.617+0000 INFO  Enabling HTTPS on port 7473
neo4j      | 2018-01-30 20:28:00.622+0000 INFO  Mounted REST API at: /db/manage
neo4j      | 2018-01-30 20:28:00.646+0000 INFO  Mounted unmanaged extension [com.graphaware.server] at [/graphaware]
neo4j      | 2018-01-30 20:28:00.710+0000 INFO  Mounting static content at /webadmin
neo4j      | 2018-01-30 20:28:00.781+0000 INFO  Mounting static content at /browser
elastic_container | [2018-01-30 20:28:00,802][INFO ][cluster.service          ] [Kasper Cole] new_master {Kasper Cole}{VJAN2n_xT8elCP2ugcF8qw}{172.20.0.2}{172.20.0.2:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
elastic_container | [2018-01-30 20:28:00,951][INFO ][http                     ] [Kasper Cole] publish_address {172.20.0.2:9200}, bound_addresses {0.0.0.0:9200}
elastic_container | [2018-01-30 20:28:00,953][INFO ][node                     ] [Kasper Cole] started
elastic_container | [2018-01-30 20:28:00,968][INFO ][gateway                  ] [Kasper Cole] recovered [0] indices into cluster_state
neo4j      | 2018-01-30 20:28:03.778+0000 INFO  Remote interface ready and available at http://0.0.0.0:7474/
```

```
ikwattro@mbp666 ~> http localhost:9200
HTTP/1.1 200 OK
Content-Length: 313
Content-Type: application/json; charset=UTF-8

{
    "cluster_name": "docker",
    "name": "Kasper Cole",
    "tagline": "You Know, for Search",
    "version": {
        "build_hash": "fcc01dd81f4de6b2852888450ce5a56436fd5852",
        "build_snapshot": false,
        "build_timestamp": "2016-03-29T08:49:35Z",
        "lucene_version": "5.4.1",
        "number": "2.2.2"
    }
}

ikwattro@mbp666 ~>
```

**Comment by aashish** [comment]
@ikwattro 
I am using Ubuntu 14.04 LTS.
The following are detailed logs:

```
chittimilla@chittimilla:~/graph-aided-search-demo$ docker network create --driver bridge gas
9849ad70f06346b70ebd9eb2d3b362aa60e4b68e190af3be582dac301558daec
chittimilla@chittimilla:~/graph-aided-search-demo$ export NETWORK=gas
chittimilla@chittimilla:~/graph-aided-search-demo$ set -x NETWORK "gas"
++ __vte_prompt_command
+++ __vte_osc7
++++ __vte_urlencode /home/chittimilla/graph-aided-search-demo
++++ LC_ALL=C
++++ str=/home/chittimilla/graph-aided-search-demo
++++ '[' -n /home/chittimilla/graph-aided-search-demo ']'
++++ safe=/home/chittimilla/graph-aided-search-demo
++++ printf %s /home/chittimilla/graph-aided-search-demo
++++ str=
++++ '[' -n '' ']'
++++ '[' -n '' ']'
+++ printf '\033]7;file://%s%s\a' chittimilla /home/chittimilla/graph-aided-search-demo
++ printf '\033]0;%s@%s:%s\007%s' chittimilla chittimilla /home/chittimilla/graph-aided-search-demo ''
chittimilla@chittimilla:~/graph-aided-search-demo$ docker-compose up
+ docker-compose up
Pulling neo4j (neo4j:2.3.2-enterprise)...
2.3.2-enterprise: Pulling from library/neo4j
723254a2c089: Pull complete
abe15a44e12f: Pull complete
409a28e3cc3d: Pull complete
a9511c68044a: Pull complete
9d1b16e30bc8: Pull complete
0fc5a09c9242: Pull complete
d34976006493: Pull complete
3b70003f0c10: Pull complete
d31c2020f2c7: Pull complete
8a2274cd5a97: Pull complete
ca4c348e78d5: Pull complete
c29c7bfc233b: Pull complete
80991cd7cd32: Pull complete
Digest: sha256:8749aa6609a304acaff9ac98118466fb3d20975acac2337233a94e23964a5245
Status: Downloaded newer image for neo4j:2.3.2-enterprise
Pulling elastic (elasticsearch:2.2.2)...
2.2.2: Pulling from library/elasticsearch
386a066cd84a: Pull complete
75ea84187083: Pull complete
3e2e387eb26a: Pull complete
eef540699244: Pull complete
1624a2f8d114: Pull complete
7018f4ec6e0a: Pull complete
6ca3bc2ad3b3: Pull complete
424638b495a6: Pull complete
2ff72d0b7bea: Pull complete
9d25542ccc02: Pull complete
7764c111a5c7: Pull complete
a076ea41b544: Pull complete
4841e9c2a909: Pull complete
ed491141ede1: Pull complete
Digest: sha256:c243ff1ee18aed0680dcbe0abaeacdbf59fa6b35a2a902262787f841de6d7b88
Status: Downloaded newer image for elasticsearch:2.2.2
Creating neo4j ... done
Creating elastic_container ... 
Attaching to elastic_container, neo4j
neo4j      | WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
neo4j      | Starting Neo4j Server console-mode...
elastic_container | Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
elastic_container | Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
elastic_container | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
elastic_container | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
elastic_container | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
elastic_container | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
elastic_container | 	at java.nio.file.Files.createDirectory(Files.java:674)
elastic_container | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
elastic_container | 	at java.nio.file.Files.createDirectories(Files.java:767)
elastic_container | 	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
elastic_container | 	at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
elastic_container | 	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:248)
elastic_container | 	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
elastic_container | 	at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:196)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
elastic_container | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
elastic_container | Refer to the log for complete error details.
neo4j      | 2018-01-31 07:50:55.894+0000 INFO  No SSL certificate found, generating a self-signed certificate..
neo4j      | 2018-01-31 07:50:56.820+0000 INFO  Initiating metrics..



elastic_container exited with code 1
elastic_container | Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
elastic_container | Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
elastic_container | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
elastic_container | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
elastic_container | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
elastic_container | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
elastic_container | 	at java.nio.file.Files.createDirectory(Files.java:674)
elastic_container | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
elastic_container | 	at java.nio.file.Files.createDirectories(Files.java:767)
elastic_container | 	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
elastic_container | 	at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
elastic_container | 	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:248)
elastic_container | 	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
elastic_container | 	at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:196)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
elastic_container | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
elastic_container | Refer to the log for complete error details.
elastic_container | Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
elastic_container | Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
elastic_container | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
elastic_container | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
elastic_container | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
elastic_container | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
elastic_container | 	at java.nio.file.Files.createDirectory(Files.java:674)
elastic_container | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
elastic_container | 	at java.nio.file.Files.createDirectories(Files.java:767)
elastic_container | 	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
elastic_container | 	at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
elastic_container | 	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:248)
elastic_container | 	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
elastic_container | 	at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:196)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167)
elastic_container | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
elastic_container | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
elastic_container | Refer to the log for complete error details.
```

**Comment by aashish** [comment]
@ikwattro 
resolved the issue and raised Pull Request [fix for Unable to access 'path.scripts'](https://github.com/graphaware/graph-aided-search-demo/pull/2)

Please feel free to review and comment.

Thanks,
Aashish
